apiVersion: apps/v1
kind: Deployment
metadata:
  name: pod-injector
  namespace: injector
spec:
  selector:
    matchLabels:
      app: pod-injector
  replicas: 1
  template:
    metadata:
      labels:
        app: pod-injector
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      restartPolicy: Always
      containers:
      - name: authn-server
        image: jianshao/pod-injector:0.0.1
        ports:
        - containerPort: 8443
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 10m
            memory: 100Mi

---
apiVersion: v1
kind: Service
metadata:
  name: pod-injector
  labels:
    app: pod-injector
  namespace: injector
spec:
  ports:
  - name: http
    port: 8443
  selector:
    app: pod-injector
