apiVersion: v1
kind: ConfigMap
metadata:
  name: injection-config
  namespace: injector
data:
  injection.yaml: |
    podInjection:
      initContainers:
      - name: copy-file-to-shared
        image: jianshao/demo-modifier:0.1.1
        command:
        - /bin/sh
        - -c
        - cp /files/* /shared/
        volumeMounts:
        - name: injected-volume
          mountPath: /shared
      volumes:
      - name: injected-volume
        volumeSource:
          emptyDir: {}
      volumeMountPatchs:
        main:
        - name: injected-volume
          mountPath: /www/templates

  patch.json: |
    [
      {
        "op": "add",
        "path": "/metadata/labels/injected",
        "value": "true"
      },
      {
        "op": "add",
        "path": "/spec/initContainers",
        "value": [
          {
            "name": "copy-file-to-shared",
            "image": "jianshao/demo-modifier:0.1.1",
            "command": [
              "/bin/sh",
              "-c",
              "cp /files/* /shared/"
            ],
            "resources": {},
            "volumeMounts": [
              {
                "name": "injected-volume",
                "mountPath": "/shared"
              }
            ]
          }
        ]
      },
      {
        "op": "add",
        "path": "/spec/volumes/-",
        "value": {
          "name": "injected-volume"
        }
      },
      {
        "op": "add",
        "path": "/spec/containers/0/volumeMounts/-",
        "value": {
          "name": "injected-volume",
          "mountPath": "/www/templates"
        }
      }
    ]
