apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
webhooks:
- name: inject-pod
  admissionReviewVersions:
    - v1
  clientConfig:
    url: http://
    # service:
    #   name: pod-injector
    #   namespace: injector
    #   path: /inject
    #   port: 8000
  rules:
  - operations:
    - CREATE
    apiGroups:
    - ""
    apiVersions:
    - v1
    resources:
    - pods
    scope: "*"
  sideEffects: None
  