apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: pod-injector
  namespace: injector
webhooks:
- name: namespace.pod-inject.jianshaow.github.io
  namespaceSelector:
    matchExpressions:
    - key: injection
      operator: In
      values:
      - enabled
  objectSelector:
    matchExpressions:
    - key: sidecar.injection
      operator: NotIn
      values:
      - "false"
  admissionReviewVersions:
    - v1
  clientConfig:
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURtVENDQW9HZ0F3SUJBZ0lVVThDSTErOUI0OElMYUh0QTRyeXlmQVJLWW9Bd0RRWUpLb1pJaHZjTkFRRUwKQlFBd1hERUxNQWtHQTFVRUJoTUNRMDR4Q3pBSkJnTlZCQWdNQWtkRU1Rc3dDUVlEVlFRSERBSkhXakVPTUF3RwpBMVVFQ2d3RlEyeHZkV1F4RVRBUEJnTlZCQXNNQ0VsdWFtVmpkRzl5TVJBd0RnWURWUVFEREFkc2IyTmhiRU5CCk1CNFhEVEl4TURrd01UQTNNalV5TlZvWERUTXhNRGd6TURBM01qVXlOVm93WERFTE1Ba0dBMVVFQmhNQ1EwNHgKQ3pBSkJnTlZCQWdNQWtkRU1Rc3dDUVlEVlFRSERBSkhXakVPTUF3R0ExVUVDZ3dGUTJ4dmRXUXhFVEFQQmdOVgpCQXNNQ0VsdWFtVmpkRzl5TVJBd0RnWURWUVFEREFkc2IyTmhiRU5CTUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGCkFBT0NBUThBTUlJQkNnS0NBUUVBMGdsd1JrQ2ZwQ0hZaFhncWg0NHIwRHdCb1Z5cUlBbkI5ODBFdXY2ZnRnV2gKQnN2TStldys1UThBMHBFQzh3ZUcyRS80VHFvMTJiejViN0k3T05KSjVSZmhwdEJNTTBtS0ZheWVmL0N4VmRBVQpFS210WE4zYnFTeGhwcUpQT0R6dWMrTm5lWSt5MTRYcEF2REI5WHZzWlpPaWFNSlRQNi9xOXN3azB0Nk84dVErClNYVUxuWms1d0hrT1hoOGttUFhsMUQ3ZWZKZWhPbDcvWlNNcjNtaGtpb254MW5kbTJWY0M0NTl1SERUZlVuYUQKOWc2Z3JnS1FIY3lFT2tUc24xOTZJZk5USHFJWnByL3R6UVZoVmlQSVpZdkwzNE9ua2dQOXhxdGswNUhqdEpWRwpFdVJtb2w4ODM5bUZGRjNWOEdSQUkyWDJmdUhzV0ZCMXk4Z1pHS0phL3dJREFRQUJvMU13VVRBZEJnTlZIUTRFCkZnUVVFZ3U2aE9LQjNTVDNmUUNuOTBhdGRwbm55WVV3SHdZRFZSMGpCQmd3Rm9BVUVndTZoT0tCM1NUM2ZRQ24KOTBhdGRwbm55WVV3RHdZRFZSMFRBUUgvQkFVd0F3RUIvekFOQmdrcWhraUc5dzBCQVFzRkFBT0NBUUVBbXpFYgpwZnNqVEZEN1pnMktkR2V3d0hwb2dXVys0WUtXcHlZWFl5S0psMFRqVDNONW5vY2Rjcjg5ZjNCZ3BpOGtiT0Z0CkV0VHp6R2paZU9zdTdKdUZKbTU0NXZlbkNVN0o4aGVYQ0FJcGpUekgzM1lWa21GOVB6NDE2MVFqcC9BeFExMXoKMGtpT0ZCenBSSE0xK2djM0dqV3poZlVWQXpNbXNOSlJLdXBZcngrMWRac01mRm1yUkMvNW1HeWxLVE1OaWU1SQpSd0lRenZTMVB5UlQ5S29yYUFIdGNkODA1cUpoRGk2L2FqcEZIK2hRdFlnU2tvb2IvMWI3a01ZMVVDMkEvWWVXClBnUFo5eXI4NWJuTXc4TGNnZ3VNeVhvRDdGS1NKaG5ZVFMydGtuVzFjUUJmSnhFN0llaTRHeXlXdEVtTmFIWlYKYkM4VEVVUlc1RUxPTWJ2bjVBPT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
    url: https://100.98.137.140:8443/inject
    # service:
    #   name: pod-injector
    #   namespace: injector
    #   path: /inject
    #   port: 8443
  rules:
  - operations:
    - CREATE
    apiGroups:
    - ""
    apiVersions:
    - v1
    resources:
    - pods
    scope: Namespaced
  sideEffects: None
  