apiVersion: v1
kind: Pod
metadata:
  name: sleep
spec:
  containers:
  - name: main
    image: jianshao/demo-app:0.0.1
    resources:
      requests:
        cpu: 100m
        memory: 50Mi
      limits:
        cpu: 100m
        memory: 50Mi
    volumeMounts:
      - mountPath: /test
        name: test-cm
      - mountPath: /certs
        name: test-secret
  volumes:
  - name: test-cm
    configMap:
      name: test-cm
  - name: test-secret
    secret:
      secretName: test-secret
